package com.flylab.domain.model

/**
 * Motor outputs generated by premotor and central complex circuits to drive movement.
 */
data class MotorCommand(
    val forwardVelocityMmS: Float = 0.0f,     // Adult walking velocity [0 .. 35 mm/s]
    val angularVelocityRadS: Float = 0.0f,    // Turning rate in radians/s [-10.0 .. +10.0]
    val proboscisExtension: Float = 0.0f,     // Proboscis extension response (PER) [0.0 .. 1.0]
    val wingBeatFrequencyHz: Float = 0.0f,    // 0.0 if grounded, ~200 Hz if in flight
    override val evidence: ScientificEvidence = ScientificEvidence(
        level = ProvenanceLevel.PUBLISHED,
        citation = "Bidaye et al. (2014) Science 344:97-101; Mendes et al. (2013) eLife.",
        notes = "Drosophila walking kinematics and steering angle velocity ranges."
    )
) : ProvenanceTagged {
    init {
        require(forwardVelocityMmS >= -5.0f && forwardVelocityMmS <= 45.0f) {
            "Forward velocity out of physiological bounds: $forwardVelocityMmS"
        }
        require(proboscisExtension in 0.0f..1.0f) {
            "Proboscis extension must be in [0, 1], was $proboscisExtension"
        }
    }

    companion object {
        val IDLE = MotorCommand()
        val WALK_FORWARD = MotorCommand(forwardVelocityMmS = 18.0f)
        val TURN_RIGHT = MotorCommand(forwardVelocityMmS = 5.0f, angularVelocityRadS = 2.5f)
        val TURN_LEFT = MotorCommand(forwardVelocityMmS = 5.0f, angularVelocityRadS = -2.5f)
    }
}
